[LICENSE](https://raw.githubusercontent.com/computational-sediment-hyd/a-rudimentary-knowledge-of-river-bed-variation/master/LICENSE)

In [1]:
from IPython.display import IFrame

---

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#沖積河川の砂州形成の数値実験" data-toc-modified-id="沖積河川の砂州形成の数値実験-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>沖積河川の砂州形成の数値実験</a></span><ul class="toc-item"><li><span><a href="#支配方程式" data-toc-modified-id="支配方程式-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>支配方程式</a></span><ul class="toc-item"><li><span><a href="#流水" data-toc-modified-id="流水-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>流水</a></span></li><li><span><a href="#流砂、河床変動" data-toc-modified-id="流砂、河床変動-1.1.2"><span class="toc-item-num">1.1.2&nbsp;&nbsp;</span>流砂、河床変動</a></span></li></ul></li><li><span><a href="#計算条件" data-toc-modified-id="計算条件-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>計算条件</a></span></li><li><span><a href="#計算結果と考察" data-toc-modified-id="計算結果と考察-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>計算結果と考察</a></span><ul class="toc-item"><li><span><a href="#砂州形成開始時の水深、河床変動量の平面空間分布" data-toc-modified-id="砂州形成開始時の水深、河床変動量の平面空間分布-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>砂州形成開始時の水深、河床変動量の平面空間分布</a></span></li><li><span><a href="#概ね平衡状態時の水深、河床変動量の平面空間分布" data-toc-modified-id="概ね平衡状態時の水深、河床変動量の平面空間分布-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>概ね平衡状態時の水深、河床変動量の平面空間分布</a></span></li><li><span><a href="#砂州形成過程：gif動画" data-toc-modified-id="砂州形成過程：gif動画-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>砂州形成過程：gif動画</a></span></li></ul></li><li><span><a href="#まとめと課題" data-toc-modified-id="まとめと課題-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>まとめと課題</a></span></li></ul></li></ul></div>

## 沖積河川の砂州形成の数値実験

### 支配方程式

#### 流水
 - 平面二次元水深平均流モデル
 
#### 流砂、河床変動

 - 河床位方程式
 - 掃流砂のみ、単一粒径、平衡流砂量式MPM式
 - 限界掃流力に局所勾配の影響を考慮する。**砂州の計算では最も重要な要素でこれがないと砂州が計算できない。** [芦田, 江頭, 劉の方法](https://www.jstage.jst.go.jp/article/prohe1990/35/0/35_0_383/_article/-char/ja)を基本に若干の修正を加えた。
 - 斜面崩壊の影響を考慮する。後述するCASE3のみに影響する。
崩壊の向き、量の考え方は[関根の方法](https://www.jstage.jst.go.jp/article/prohe1990/47/0/47_0_637/_article/-char/ja/)を基本とするが、崩壊量は流砂量に付加するのではなく、瞬時に崩壊が生じるものとした。

### 計算条件

斐伊川下流部をモデルに設定した。初期水深を変えた3ケースの計算を行った。

 - 河床勾配：1/670
 
 - 河床材料：2mm
 
 - 川幅：90m
 - 延長：1800m
 
 - 格子サイズ: 5m
 
 - 境界条件
     * 上下流端：周期境界条件
     * 左右岸境界：壁境界
     
 - 初期条件
     * 河床：最大値を粒径とした乱数を与える
     * 初期水深
         - CASE1 : 1.0m
         - CASE2 : 0.6m
         - CASE3 : 0.3m
     * 無次元掃流力：
         - CASE1 : 0.452
         - CASE2 : 0.271
         - CASE3 : 0.136


 - 計算ケースごとの川幅水深比と無次元掃流力の関係を[黒木, 岸](https://www.jstage.jst.go.jp/article/jscej1969/1984/342/1984_342_87/_article/-char/ja/)
の線形安定化解析に基づく砂州形態の分類図にプロットした。
 - CASE1は単列砂州、CASE2、3は複列砂州の領域となる。

<div align="center">
<img src="https://raw.githubusercontent.com/computational-sediment-hyd/a-rudimentary-knowledge-of-river-bed-variation/master/figSandbarSimulation/sandbaraddpoint.png" width="500">
</div>

### 計算結果と考察

#### 砂州形成開始時の水深、河床変動量の平面空間分布

 - 計算開始から300時間後の計算結果を下図に示す。
 - 砂州の列数は、CASE1：1列、CASE2：2列、CASE3：3列以上となっており、卓越する成分が明確に把握できる。
 - この状態が上記領域区分の示すところ？（与えた擾乱のうち、どの成分が卓越するか）

 - CASE1

In [2]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE1-300h.html",width=1000,height=350)

 - CASE2

In [3]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE2-300h.html",width=1000,height=350)

 - CASE3

In [4]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE3-300h.html",width=1000,height=350)

#### 概ね平衡状態時の水深、河床変動量の平面空間分布

 - 計算開始時の2000時間後の計算結果を下図に示す。
 - CASE1およびCASE2ともに、砂州の列数が1列となっている。一方、CASE3は周期性を持たない複雑な流路を示す。
 - CASE2は初期は列数が2列であったが時間の経過とともに個々の砂州が干渉し、1列の砂州が形成される。
 - CASE3では、初期は複数の流路が出現したが、浮州（ドライベッド）の出現をきっかけに流路の変化が複雑化し、最終的には複数の流路が粗発生する。

 - CASE1

In [5]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE1-2000h.html",width=1000,height=350)

 - CASE2

In [6]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE2-2000h.html",width=1000,height=350)

 - CASE3

In [7]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE3-2000h.html",width=1000,height=350)

#### 砂州形成過程：gif動画

 - CASE1
 
     - 500時間後には平衡状態に達してそれ以降は周期的な変化を示す。

In [8]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE1.gif",width=1000,height=350)

 - CASE2
 
    - 1000時間後に状態に達する。CASE1と比べて砂州の移動速度が遅い。
    - 2列の砂州が維持できない。なぜ？

In [9]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE2.gif",width=1000,height=350)

 -  CASE3
 
  - 5700時間後までの計算を実施しているが平衡状態に達していない。周期的な変動ではないため、平衡状態は存在しない可能性がある。
  - 流路変動は側岸浸食によって生じるため、その速度は非常に遅い。
  - もう少し分析が必要。さらに長期の計算を実施予定。

In [10]:
IFrame("https://computational-sediment-hyd.github.io/a-rudimentary-knowledge-of-river-bed-variation/figSandbarSimulation/CASE3.gif",width=1000,height=350)

### まとめと課題
 - 任意の条件下における砂州の平衡状態を数値計算によって検証した。
 - CASE1は形成条件のとおり、単列砂州が形成される。
 - CASE2は複列砂州条件では安定的な複列砂州は形成されず、長期的にはCASE1と同様に単列砂州となる。では、斐伊川のような多列砂州はなぜ維持されるのか？非定常の影響？他の乱れの影響？もう少し検討が必要。
 - CASE3は、浮州が出現、つまり砂州高＞水深となり、複雑な地形を示す。個人的には、これが流路＝河川が形成される機構ではないか考えている。さらにテスト計算を実施予定。

------
 - memo

In [11]:
import numpy as np

In [12]:
ib = 1/670
B = 90

h = np.array( [1.0, 0.6, 0.3] )
d = 2/1000

tau = h * ib / 1.65/ d
tau

array([0.45228403, 0.27137042, 0.13568521])

In [13]:
B*ib**0.2/h

array([24.492186, 40.82031 , 81.64062 ])

In [14]:
B/h

array([ 90., 150., 300.])

In [15]:
from scipy import special

In [16]:
x = (B/d)**(-0.45)*9.34*np.exp( 2.53*special.erf((np.log10(B/h) - 1.22)/0.594)) 

In [17]:
x * h

array([0.7705053 , 0.53485284, 0.28135338])